/** Formules d'abonnement insérées en base au premier lancement (voir scripts/seed.ts). */
export const planCatalog = [
  {
    slug: "enseignant",
    name: "Enseignant·e",
    tagline: "Tous les outils, pour une personne.",
    description: "Pour s'équiper individuellement, sur tous ses appareils, sans passer par l'établissement.",
    priceMonthlyCents: 490,
    priceYearlyCents: 4900,
    features: [
      "Les 12 outils, web et bureau",
      "Signatures, OCR et caviardage inclus",
      "Fichiers jusqu'à 200 Mo · 10 Go de stockage",
      "1 utilisateur·trice, tous ses appareils",
      "Paiement par carte",
    ],
    highlight: false,
    quoteOnly: false,
    sortOrder: 1,
  },
  {
    slug: "etablissement",
    name: "Établissement",
    tagline: "Toute l'école, une seule licence.",
    description: "Secrétariat, direction, doyens et corps enseignant : une licence par établissement, sans plafond.",
    priceMonthlyCents: 14900,
    priceYearlyCents: 149000,
    features: [
      "Collaborateur·trice·s illimités",
      "Connexion unique via l'identité cantonale",
      "Espace documentaire de l'établissement · 1 To",
      "Console d'administration et journal d'audit",
      "Contrat de sous-traitance LPD / LPrD",
      "Facturation sur bon de commande",
    ],
    highlight: true,
    quoteOnly: false,
    sortOrder: 2,
  },
  {
    slug: "canton",
    name: "Canton",
    tagline: "Tous les établissements et les services de l'État.",
    description: "Un déploiement centralisé pour l'ensemble du canton, avec un accompagnement dédié.",
    priceMonthlyCents: 0,
    priceYearlyCents: 0,
    features: [
      "Tout Établissement, pour tous les établissements",
      "Déploiement centralisé et gestion par la DGEO / DGEP",
      "Formation des secrétariats et référent·e·s",
      "Engagement de disponibilité et support dédié",
      "Hébergement dédié possible",
      "Fiche technique pour les marchés publics",
    ],
    highlight: false,
    quoteOnly: true,
    sortOrder: 3,
  },
];
