/** Formules d'abonnement insérées en base au premier lancement (voir scripts/seed.ts). */
export const planCatalog = [
  {
    slug: "essentiel",
    name: "Essentiel",
    tagline: "Tous les outils du quotidien, pour une personne.",
    description: "Éditez, fusionnez, convertissez et protégez vos PDF sans limite de documents.",
    priceMonthlyCents: 990,
    priceYearlyCents: 9900,
    features: [
      "Éditeur complet, web et bureau",
      "Fusion, division, conversion et compression illimitées",
      "Formulaires, annotations et protection",
      "Fichiers jusqu'à 100 Mo · 5 Go de stockage",
      "1 utilisateur, tous ses appareils",
    ],
    highlight: false,
    sortOrder: 1,
  },
  {
    slug: "pro",
    name: "Pro",
    tagline: "Signature, OCR et caviardage pour les professionnels.",
    description: "Tout Essentiel, plus les outils avancés dont les métiers réglementés ont besoin.",
    priceMonthlyCents: 1990,
    priceYearlyCents: 19900,
    features: [
      "Tout Essentiel",
      "Signatures électroniques illimitées avec audit",
      "OCR multilingue et caviardage définitif",
      "Comparaison de versions",
      "Fichiers jusqu'à 1 Go · 100 Go de stockage",
      "Support prioritaire sous 4 h ouvrées",
    ],
    highlight: true,
    sortOrder: 2,
  },
  {
    slug: "equipe",
    name: "Équipe",
    tagline: "Cinq utilisateurs, un espace partagé, une administration.",
    description: "Pour les fiduciaires, études et PME qui travaillent leurs documents à plusieurs.",
    priceMonthlyCents: 4990,
    priceYearlyCents: 49900,
    features: [
      "Tout Pro, pour 5 utilisateurs",
      "Espace documentaire partagé · 1 To",
      "Connexion unique (SSO) Google et Microsoft",
      "Journal d'audit et gestion centralisée",
      "Contrat de sous-traitance LPD / RGPD",
      "Utilisateurs supplémentaires : CHF 8.– / mois",
    ],
    highlight: false,
    sortOrder: 3,
  },
];
