/** Formules d'abonnement insérées en base au premier lancement (voir scripts/seed.ts). */
export const planCatalog = [
  {
    slug: "essentiel",
    name: "Essentiel",
    tagline: "Un rendez-vous mensuel avec vous-même.",
    description: "La formule idéale pour instaurer une routine de soin régulière, sans y penser.",
    priceMonthlyCents: 8900,
    priceYearlyCents: 89000,
    features: [
      "1 soin visage ou massage (60 min) par mois",
      "10 % sur la boutique et les soins à l'unité",
      "Accès aux ateliers senteurs au tarif membre",
      "Sans engagement, résiliable à tout moment",
    ],
    highlight: false,
    sortOrder: 1,
  },
  {
    slug: "signature",
    name: "Signature",
    tagline: "Le rythme juste pour des résultats visibles.",
    description: "Deux soins par mois, la priorité de réservation et un atelier par trimestre.",
    priceMonthlyCents: 15900,
    priceYearlyCents: 159000,
    features: [
      "2 soins (60 min) par mois, au choix",
      "1 atelier création de senteur par trimestre",
      "15 % sur la boutique et les soins à l'unité",
      "Réservation prioritaire",
      "Synergie d'huiles personnalisée offerte",
    ],
    highlight: true,
    sortOrder: 2,
  },
  {
    slug: "prestige",
    name: "Prestige",
    tagline: "L'atelier, comme une seconde maison.",
    description: "Pour celles et ceux qui veulent une prise en charge complète, tout au long de l'année.",
    priceMonthlyCents: 28900,
    priceYearlyCents: 289000,
    features: [
      "4 soins (60 min) par mois, ou 2 rituels (120 min)",
      "Ateliers senteurs illimités",
      "20 % sur la boutique et les soins à l'unité",
      "Réservation prioritaire et créneaux du samedi garantis",
      "Bilan aromathérapie semestriel",
      "Invitations aux soirées privées de l'atelier",
    ],
    highlight: false,
    sortOrder: 3,
  },
];
